//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienBangKiemKe
    {
        public string MaKK { get; set; }
        public string MaKho { get; set; }
        public string MaSP { get; set; }
        public string TenNV { get; set; }
        public string TenBienBang { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    
        public virtual ChiTietBienBang ChiTietBienBang { get; set; }
    }
}
