//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienBangKiemKe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienBangKiemKe()
        {
            this.ChiTietBienBangs = new HashSet<ChiTietBienBang>();
        }
    
        public string MaKK { get; set; }
        public string MaKho { get; set; }
        public string MaNVLap { get; set; }
        public string TenBienBang { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBienBang> ChiTietBienBangs { get; set; }
    }
}
