//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKiemKe
    {
        public string MaCTKK { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SLTon { get; set; }
        public Nullable<int> SLThucTe { get; set; }
        public Nullable<int> ChenhLech { get; set; }
        public string LyDo { get; set; }
        public string MaKK { get; set; }
    
        public virtual BanKiemKe BanKiemKe { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
