//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietChuyenGiao
    {
        public int MaCTDVC { get; set; }
        public string MaGH { get; set; }
        public string MaDH { get; set; }
        public Nullable<double> TongTienThu { get; set; }
    
        public virtual ChuyenGiao ChuyenGiao { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
