//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenGiao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenGiao()
        {
            this.DonHangs = new HashSet<DonHang>();
            this.NhanVienGHs = new HashSet<NhanVienGH>();
        }
    
        public string MaGH { get; set; }
        public string MaNVLap { get; set; }
        public string MaPT { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<double> TienThu { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string KhuVucGiao { get; set; }
    
        public virtual PhuongTienGH PhuongTienGH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVienGH> NhanVienGHs { get; set; }
    }
}
