//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhSo
    {
        public System.DateTime ThoiGian { get; set; }
        public string MaDL { get; set; }
        public Nullable<double> TongDoanhSo { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
    }
}
