//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangGiao
    {
        public int STT { get; set; }
        public string MaGH { get; set; }
        public string MaDH { get; set; }
        public string MaNV { get; set; }
        public string MaPT { get; set; }
        public string DiemGiao { get; set; }
        public Nullable<bool> TrangThaiXD { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<double> TienThu { get; set; }
        public string XacNhanGH { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual NhanVienGH NhanVienGH { get; set; }
        public virtual PhuongTienGH PhuongTienGH { get; set; }
    }
}
