//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.DanhSachGiaoHangs = new HashSet<DanhSachGiaoHang>();
            this.PhieuCongNoes = new HashSet<PhieuCongNo>();
            this.ThongKes = new HashSet<ThongKe>();
        }
    
        public string MaDH { get; set; }
        public string MaSP { get; set; }
        public string MaDL { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGiaApDung { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string TrangThai { get; set; }
        public string DiemGiao { get; set; }
        public string TenNV { get; set; }
        public string TinhTrangThanhToan { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachGiaoHang> DanhSachGiaoHangs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuCongNo> PhieuCongNoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKe> ThongKes { get; set; }
    }
}
