//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HoaDon
    {
        [DisplayName("Mã hóa đơn")]
        public string MaHD { get; set; }

        [DisplayName("Mã đơn hàng")]
        public string MaDH { get; set; }

        [DisplayName("Tên đại lý tiếp nhận")]
        public string TenDVTiepNhan { get; set; }

        [DisplayName("Tổng hóa đơn")]
        public Nullable<double> TongTien { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
