//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {

        public string MaKho { get; set; }
        public string MaNV { get; set; }
        public string MaSP { get; set; }
        public string TenKho { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SLTon { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
