//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LoaiDL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiDL()
        {
            this.DaiLies = new HashSet<DaiLy>();
        }
        [DisplayName("Mã loại đại lý")]
        public string MaLoaiDL { get; set; }
        [DisplayName("Tên đại lý")]
        public string TenDaiLy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaiLy> DaiLies { get; set; }
    }
}
