//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyDLEntities2 : DbContext
    {
        public QuanLyDLEntities2()
            : base("name=QuanLyDLEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCao> BaoCaos { get; set; }
        public virtual DbSet<BienBangKiemKe> BienBangKiemKes { get; set; }
        public virtual DbSet<ChiTietBienBang> ChiTietBienBangs { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<ChiTietKho> ChiTietKhoes { get; set; }
        public virtual DbSet<ChiTietPhieuNhapXuat> ChiTietPhieuNhapXuats { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<ChuyenGiao> ChuyenGiaos { get; set; }
        public virtual DbSet<DaiLy> DaiLies { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<LoaiDL> LoaiDLs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhanVienGH> NhanVienGHs { get; set; }
        public virtual DbSet<PhieuCongNo> PhieuCongNoes { get; set; }
        public virtual DbSet<PhieuNhapXuat> PhieuNhapXuats { get; set; }
        public virtual DbSet<PhuongTienGH> PhuongTienGHs { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
    
        public virtual ObjectResult<pr_SapxepDonHang_Result> pr_SapxepDonHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SapxepDonHang_Result>("pr_SapxepDonHang");
        }
    
        public virtual int sp_capnhat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_capnhat");
        }
    
        public virtual int sp_CapnhatDL(string maDL, string loaiDL, string user, string pass, string tenDL, string diachi, string sdt, string email, string hinhanh)
        {
            var maDLParameter = maDL != null ?
                new ObjectParameter("MaDL", maDL) :
                new ObjectParameter("MaDL", typeof(string));
    
            var loaiDLParameter = loaiDL != null ?
                new ObjectParameter("LoaiDL", loaiDL) :
                new ObjectParameter("LoaiDL", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var tenDLParameter = tenDL != null ?
                new ObjectParameter("tenDL", tenDL) :
                new ObjectParameter("tenDL", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var hinhanhParameter = hinhanh != null ?
                new ObjectParameter("hinhanh", hinhanh) :
                new ObjectParameter("hinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapnhatDL", maDLParameter, loaiDLParameter, userParameter, passParameter, tenDLParameter, diachiParameter, sdtParameter, emailParameter, hinhanhParameter);
        }
    
        public virtual int sp_XoaDL(string maDL)
        {
            var maDLParameter = maDL != null ?
                new ObjectParameter("MaDL", maDL) :
                new ObjectParameter("MaDL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaDL", maDLParameter);
        }
    
        public virtual ObjectResult<sp_CongNoDenHan_Result> sp_CongNoDenHan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CongNoDenHan_Result>("sp_CongNoDenHan");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_CountCN(string madl)
        {
            var madlParameter = madl != null ?
                new ObjectParameter("madl", madl) :
                new ObjectParameter("madl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CountCN", madlParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_DHtheotinhtrang(string thanhtoan)
        {
            var thanhtoanParameter = thanhtoan != null ?
                new ObjectParameter("thanhtoan", thanhtoan) :
                new ObjectParameter("thanhtoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_DHtheotinhtrang", thanhtoanParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_DoanhThutrongthang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_DoanhThutrongthang");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_DonHangtrongngay(string thanhtoan)
        {
            var thanhtoanParameter = thanhtoan != null ?
                new ObjectParameter("thanhtoan", thanhtoan) :
                new ObjectParameter("thanhtoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_DonHangtrongngay", thanhtoanParameter);
        }
    
        public virtual ObjectResult<sp_LocDonHang_Result> sp_LocDonHang(string thang, string thanhtoan, string tinhtrang)
        {
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            var thanhtoanParameter = thanhtoan != null ?
                new ObjectParameter("thanhtoan", thanhtoan) :
                new ObjectParameter("thanhtoan", typeof(string));
    
            var tinhtrangParameter = tinhtrang != null ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LocDonHang_Result>("sp_LocDonHang", thangParameter, thanhtoanParameter, tinhtrangParameter);
        }
    
        public virtual ObjectResult<sp_LocPhieuCongNo_Result> sp_LocPhieuCongNo(string thang, string thanhtoan, string madl)
        {
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            var thanhtoanParameter = thanhtoan != null ?
                new ObjectParameter("thanhtoan", thanhtoan) :
                new ObjectParameter("thanhtoan", typeof(string));
    
            var madlParameter = madl != null ?
                new ObjectParameter("madl", madl) :
                new ObjectParameter("madl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LocPhieuCongNo_Result>("sp_LocPhieuCongNo", thangParameter, thanhtoanParameter, madlParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_SoDHDaiLy(string madl)
        {
            var madlParameter = madl != null ?
                new ObjectParameter("madl", madl) :
                new ObjectParameter("madl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_SoDHDaiLy", madlParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_SumCN(string madl)
        {
            var madlParameter = madl != null ?
                new ObjectParameter("madl", madl) :
                new ObjectParameter("madl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_SumCN", madlParameter);
        }
    
        public virtual ObjectResult<sp_TaoCongNo_Result> sp_TaoCongNo(string madl, Nullable<double> tienno, Nullable<System.DateTime> hantra, Nullable<System.DateTime> ngaylap, string thang)
        {
            var madlParameter = madl != null ?
                new ObjectParameter("madl", madl) :
                new ObjectParameter("madl", typeof(string));
    
            var tiennoParameter = tienno.HasValue ?
                new ObjectParameter("tienno", tienno) :
                new ObjectParameter("tienno", typeof(double));
    
            var hantraParameter = hantra.HasValue ?
                new ObjectParameter("hantra", hantra) :
                new ObjectParameter("hantra", typeof(System.DateTime));
    
            var ngaylapParameter = ngaylap.HasValue ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(System.DateTime));
    
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TaoCongNo_Result>("sp_TaoCongNo", madlParameter, tiennoParameter, hantraParameter, ngaylapParameter, thangParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_TienDHNoDaiLy(string madl, string thang)
        {
            var madlParameter = madl != null ?
                new ObjectParameter("madl", madl) :
                new ObjectParameter("madl", typeof(string));
    
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_TienDHNoDaiLy", madlParameter, thangParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
