//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe
    {
        public Nullable<System.DateTime> Ngay { get; set; }
        public string MaDH { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TongTien { get; set; }
        public int MaThongKe { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
